### ISSUE TITLE
zDiscordAPI makes it so that Spicord bot doesn't load up

### ISSUE THREAD

**Issue by dexasz** [OopsieWoopsie/Spicord#10]
Hello, I'm using zAuctionHouse plugin from spigot, and I'm encountering the issue, where Spicord doesn't load up its bot, but when I remove zAuctionHouse from the server, it works again?

They have their own discord API, not sure if its something they have to fix, or Spicord has to fix.
It's called: zDiscordAPI

**Comment by OopsieWoopsie** [comment]
Hello, I have looked for the plugins you are mentioning and I can't check zAuctionHouse because its a premium resource, but I have seen the "zDiscord API" plugin from the same author and it uses the same Discord library that Spicord uses (JDA).
Can you send me your server startup log? (you can DM me on Discord)
