### ISSUE TITLE
An illegal reflective access operation occured

### ISSUE THREAD

**Issue by LordVZlomka** [OopsieWoopsie/Spicord#44]
![image](https://user-images.githubusercontent.com/71541816/123801025-df2fd200-d8b7-11eb-862b-a400a2d92a3d.png)

**Comment by OopsieWoopsie** [comment]
Hi, that warning was previously seen on Java 11, but it seems that the Java developers decided to don't show that for legit cases and so that is not shown on Java 16, it should not cause any issue even if you decide to update to Java 16 (which is the latest version supported by spigot).

I will close this issue because this is a warning that does not cause any issues with the plugin and does not happen on newer Java versions.
