### ISSUE TITLE
Velocity 3.0.0+ support

### ISSUE THREAD

**Issue by D3adhkwen** [OopsieWoopsie/Spicord#45]
Spicord and its addons do not work on Velocity 3.0.0+. Since its already officially released, would be a good time to add support for it.

Error: https://paste.gg/p/anonymous/5860249be69a4c08a36ab7e51ed3f36e

**Comment by OopsieWoopsie** [comment]
Hi, sure! this is already on my to-do list

**Comment by OopsieWoopsie** [comment]
Hi, I have done it but not tested (lack of time), I have attached a build containing the last commits. In case you want to test, you should extract the .zip file, it contains the .jar file into it; I "zipped" it because GitHub does not allow to upload .jar files directly into comments.

Just to clarify, BanAnnouncer will not work, as I also need to code it for working on Velocity, this is just Spicord itself.

[Spicord_4.1.0.zip](https://github.com/Spicord/Spicord/files/7190754/Spicord_4.1.0.zip)

**Comment by D3adhkwen** [comment]
Test build works perfectly. Excited for the Ban Announcer update!

**Comment by DeriksonTM** [comment]
Why was my comment deleted? This problem can't be solved?

**Comment by D3adhkwen** [comment]
> Why was my comment deleted? This problem can't be solved?

Open a new issue if it is not related to Velocity 3.0.0+ support.

**Comment by OopsieWoopsie** [comment]
> Why was my comment deleted? This problem can't be solved?

Your comment was not related to this thread.

**Comment by OopsieWoopsie** [comment]
Closing this issue in favor of https://github.com/Spicord/BanAnnouncer/issues/60
