### ISSUE TITLE
Random Spicord Errors

### ISSUE THREAD

**Issue by thejtzone** [OopsieWoopsie/Spicord#62]
Using Minecraft 1.18 I Get This Error When Starting The Server: https://pastebin.com/TRmPxYsD

Plugins: https://pastebin.com/51JX3mSn

Also I'm Using PloudOS Server Hosting.

**Comment by anvorgesa** [comment]
Hi, the issue is probabaly because the hosting provider does not allow servers to perform connections to external addresses, but you can still put the required files manually, do this:
1. Download the .zip file attached on this message
2. Go to your server `plugins -> Spicord -> lib` folder
3. Paste the .jar files that are inside the .zip into the "lib" folder of Spicord

The folder hierarchy should look like this
```
plugins
└── Spicord
    ├── addons
    ├── config.toml
    └── lib
        ├── JDA-4.2.1.jar (extracted from the .zip)
        ├── rhino-1.7.12.jar (extracted from the .zip)
        ├── snakeyaml-1.26.jar (extracted from the .zip)
        └── toml4j-0.7.2.jar (extracted from the .zip)
```

Required file: [lib.zip](https://github.com/Spicord/Spicord/files/8839349/lib.zip)
