### ISSUE TITLE
Please update Spicord to JDA 5.0.0-beta.15

### ISSUE THREAD

**Issue by Emibergo02** [OopsieWoopsie/Spicord#78]
In beta 15 it has been implemented a new feature: parsing MessageEmbeds from JSON strings.
That is incredibly useful

**Comment by anvorgesa** [comment]
Sorry that I haven't seen this GH issue on time, I was not able to use my account due to the recently mandatory 2FA change made by GitHub. And had to borrow a phone just to be able to use my account again and publish a new release.
I ended up updating JDA to beta 16 as it was released an hour ago. https://github.com/Spicord/Spicord/releases/tag/5.1.2
